<!-- Copyright (C) 2013 The Libphonenumber Authors

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: David Yonge-Mallo
     @author: Shaopeng Jia
     @author: Lara Rennie

     Metadata on Short Number patterns, containing information for classifying short numbers by
     type and cost. Note that this is used in addition to the information provided by the
     PhoneNumberMetadata.xml file - patterns should not be duplicated between these files.

     Emergency numbers Wikipedia source:
     http://en.wikipedia.org/wiki/Emergency_telephone_number
-->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (generalDesc, shortCode, tollFree?, standardRate?, premiumRate?,
        carrierSpecific?, emergency?, expandedEmergency?, smsServices?)>
    <!ELEMENT generalDesc (nationalNumberPattern)>
    <!ELEMENT shortCode (possibleLengths, exampleNumber, nationalNumberPattern)>

    <!-- The following cost categories are mutually exclusive. Emergency numbers are implicitly
         considered toll free and do not need to be repeated here. Otherwise, a short number which
         does not fall into one of these categories is considered to have unknown cost. -->
    <!ELEMENT tollFree (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT standardRate (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT premiumRate (possibleLengths, exampleNumber, nationalNumberPattern)>

    <!-- The following tags are currently used to classify numbers as a particular type and need not
         be mutually exclusive. The names are provisionary only and may be revised in the future.
         -->
    <!-- carrierSpecific numbers are numbers for which the endpoint can vary by carrier. The number
         may connect to a different endpoint on another carrier, or may not work at all. -->
    <!ELEMENT carrierSpecific (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!ELEMENT emergency (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!-- Emergency numbers beyond the traditional fire-police-ambulance trio. This includes things
         like rescue helicopters and help-lines that include "emergency" in their description. -->
    <!ELEMENT expandedEmergency (possibleLengths, exampleNumber, nationalNumberPattern)>
    <!-- Used for numbers where the primary or only intended usage is to receive and/or send text
         messages (SMSs). -->
    <!ELEMENT smsServices (possibleLengths, exampleNumber, nationalNumberPattern)>

    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT possibleLengths EMPTY>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST possibleLengths national CDATA #REQUIRED>
    <!ATTLIST possibleLengths localOnly CDATA #IMPLIED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Ascension Island (AC) -->
    <!-- www.itu.int/oth/T02020000AF -->
    <territory id="AC">
      <generalDesc>
        <nationalNumberPattern>9\d\d</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            99
          )
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            99
          )
        </nationalNumberPattern>
      </tollFree>
      <!-- http://studentsabroad.state.gov/content/pdfs/911_ABROAD.pdf
           http://www.noonsite.com/Countries/AscensionIsland/?rc=GeneralInfo
           Note the 4-digit emergency numbers fit the fixed-line pattern, therefore are not
           included. This is consistent with how we handle such numbers in other countries. -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            99
          )
        </nationalNumberPattern>
      </emergency>
    </territory>

    <!-- Andorra (AD) -->
    <!-- http://www.itu.int/oth/T0202000005/en -->
    <territory id="AD">
      <generalDesc>
        <nationalNumberPattern>1\d\d</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3"/>
        <exampleNumber>110</exampleNumber>
        <nationalNumberPattern>11[0268]</nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>110</exampleNumber>
        <nationalNumberPattern>11[0268]</nationalNumberPattern>
      </tollFree>
      <!-- http://www.fco.gov.uk/en/travel-and-living-abroad/travel-advice-by-country/europe/andorra -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>110</exampleNumber>
        <nationalNumberPattern>11[0268]</nationalNumberPattern>
      </emergency>
    </territory>

    <!-- United Arab Emirates (AE) -->
    <!-- http://www.itu.int/oth/T02020000DC/en -->
    <territory id="AE">
      <generalDesc>
        <nationalNumberPattern>[149]\d{2,3}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3,4"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          112|
          445[16]|
          99[7-9]
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          112|
          99[7-9]
        </nationalNumberPattern>
      </tollFree>
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          112|
          99[7-9]
        </nationalNumberPattern>
      </emergency>
      <!-- As per online evidences, 4451 and 4456 are SMS-able short codes. -->
      <smsServices>
        <possibleLengths national="4"/>
        <exampleNumber>4450</exampleNumber>
        <nationalNumberPattern>445\d</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Afghanistan (AF) -->
    <!-- http://www.itu.int/oth/T0202000001/en -->
    <territory id="AF">
      <generalDesc>
        <nationalNumberPattern>
          [14]\d\d(?:
            \d{2}
          )?
        </nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3,5"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          1(?:
            0[02]|
            19
          )|
          40404
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          1(?:
            0[02]|
            19
          )
        </nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="5"/>
        <exampleNumber>40400</exampleNumber>
        <nationalNumberPattern>404\d\d</nationalNumberPattern>
      </carrierSpecific>
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          1(?:
            0[02]|
            19
          )
        </nationalNumberPattern>
      </emergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="5"/>
        <exampleNumber>40400</exampleNumber>
        <nationalNumberPattern>404\d\d</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Antigua & Barbuda (AG) -->
    <!-- http://www.itu.int/oth/T0202000008/en -->
    <territory id="AG">
      <generalDesc>
        <nationalNumberPattern>[19]\d\d</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>
          176|
          9(?:
            11|
            88|
            99
          )
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            88|
            99
          )
        </nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>176</nationalNumberPattern>
      </carrierSpecific>
      <!-- http://barbados.usembassy.gov/emergency-antigua_barbuda.html -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            99
          )
        </nationalNumberPattern>
      </emergency>
      <expandedEmergency>
        <possibleLengths national="3"/>
        <exampleNumber>988</exampleNumber>
        <nationalNumberPattern>988</nationalNumberPattern>
      </expandedEmergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>176</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Anguilla (AI) -->
    <!-- http://www.itu.int/oth/T0202000007/en -->
    <territory id="AI">
      <generalDesc>
        <nationalNumberPattern>[19]\d\d</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>
          176|
          9(?:
            11|
            88
          )
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            88
          )
        </nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>176</nationalNumberPattern>
      </carrierSpecific>
      <!-- http://barbados.usembassy.gov/emergency-anguilla.html -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>911</nationalNumberPattern>
      </emergency>
      <expandedEmergency>
        <possibleLengths national="3"/>
        <exampleNumber>988</exampleNumber>
        <nationalNumberPattern>988</nationalNumberPattern>
      </expandedEmergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>176</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Albania (AL) -->
    <!-- http://www.itu.int/oth/T0202000002/en -->
    <territory id="AL">
      <generalDesc>
        <nationalNumberPattern>[15]\d{2,5}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="[3-6]"/>
        <exampleNumber>110</exampleNumber>
        <nationalNumberPattern>
          1(?:
            1(?:
              6(?:
                000|
                1(?:
                  06|
                  11|
                  23
                )
              )|
              8\d\d
            )|
            65\d|
            89[12]
          )|
          5\d{4}|
          1(?:
            [1349]\d|
            2[2-9]
          )
        </nationalNumberPattern>
      </shortCode>
      <!-- All 116XXX, "European harmonized services of social" value are toll-free.
           See: https://ec.europa.eu/digital-single-market/116-helplines. -->
      <tollFree>
        <possibleLengths national="3,6"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          1(?:
            1(?:
              2|
              6[01]\d\d
            )|
            2[7-9]|
            3[15]|
            41
          )
        </nationalNumberPattern>
      </tollFree>
      <premiumRate>
        <possibleLengths national="5"/>
        <exampleNumber>50000</exampleNumber>
        <nationalNumberPattern>5\d{4}</nationalNumberPattern>
      </premiumRate>
      <!-- 123 is a ALBtelecom customer service number. -->
      <carrierSpecific>
        <possibleLengths national="3"/>
        <exampleNumber>123</exampleNumber>
        <nationalNumberPattern>123</nationalNumberPattern>
      </carrierSpecific>
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          1(?:
            12|
            2[7-9]
          )
        </nationalNumberPattern>
      </emergency>
      <!-- According to http://www.itu.int/net/itu-t/inrdb/e129_important_numbers.aspx this is for
           sea emergencies and 126 for traffic emergencies. -->
      <expandedEmergency>
        <possibleLengths national="3,6"/>
        <exampleNumber>125</exampleNumber>
        <nationalNumberPattern>
          1(?:
            16(?:
              000|
              1(?:
                06|
                11|
                23
              )
            )|
            2[56]
          )
        </nationalNumberPattern>
      </expandedEmergency>
      <smsServices>
        <possibleLengths national="3,5"/>
        <exampleNumber>131</exampleNumber>
        <nationalNumberPattern>
          131|
          5\d{4}
        </nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Armenia (AM) -->
    <!-- http://www.itu.int/oth/T020200000A/en -->
    <territory id="AM">
      <generalDesc>
        <nationalNumberPattern>[148]\d{2,4}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="[3-5]"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          (?:
            1|
            8[1-7]
          )\d\d|
          40404
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>101</exampleNumber>
        <nationalNumberPattern>10[1-3]</nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="5"/>
        <exampleNumber>40400</exampleNumber>
        <nationalNumberPattern>404\d\d</nationalNumberPattern>
      </carrierSpecific>
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>101</exampleNumber>
        <nationalNumberPattern>10[1-3]</nationalNumberPattern>
      </emergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="5"/>
        <exampleNumber>40400</exampleNumber>
        <nationalNumberPattern>404\d\d</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Angola (AO) -->
    <!-- http://www.itu.int/oth/T0202000006/en -->
    <territory id="AO">
      <generalDesc>
        <nationalNumberPattern>1\d\d</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>11[235]</nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>11[235]</nationalNumberPattern>
      </tollFree>
      <!-- http://travel.state.gov/travel/cis_pa_tw/cis/cis_1096.html -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>11[235]</nationalNumberPattern>
      </emergency>
    </territory>

    <!-- Argentina (AR) -->
    <!-- http://www.itu.int/oth/T0202000009/en -->
    <!-- http://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina#Public_utility_numbers -->
    <territory id="AR">
      <generalDesc>
        <nationalNumberPattern>[01389]\d{1,4}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="[2-5]"/>
        <exampleNumber>19</exampleNumber>
        <nationalNumberPattern>
          000|
          1(?:
            0[0-35-7]|
            1[02-5]|
            2[015]|
            3[47]|
            4[478]|
            9
          )|
          3372|
          89338|
          911
        </nationalNumberPattern>
      </shortCode>
      <!-- According to http://wikitravel.org/en/Argentina all 2 and 3 digit numbers are free,
           except for 113. -->
      <tollFree>
        <possibleLengths national="2,3"/>
        <exampleNumber>19</exampleNumber>
        <nationalNumberPattern>
          000|
          1(?:
            0[0-35-7]|
            1[0245]|
            2[015]|
            3[47]|
            4[478]|
            9
          )|
          911
        </nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="5"/>
        <exampleNumber>89300</exampleNumber>
        <nationalNumberPattern>893\d\d</nationalNumberPattern>
      </carrierSpecific>
      <!-- http://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina#Public_utility_numbers -->
      <!-- 911 is only available in some places. -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          10[017]|
          911
        </nationalNumberPattern>
      </emergency>
      <expandedEmergency>
        <possibleLengths national="3"/>
        <exampleNumber>103</exampleNumber>
        <nationalNumberPattern>
          1(?:
            0[356]|
            20|
            3[47]|
            4[478]
          )
        </nationalNumberPattern>
      </expandedEmergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="4,5"/>
        <exampleNumber>3370</exampleNumber>
        <nationalNumberPattern>
          (?:
            337|
            893\d
          )\d
        </nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- American Samoa (AS) -->
    <!-- http://www.itu.int/oth/T0202000004/en -->
    <territory id="AS">
      <generalDesc>
        <nationalNumberPattern>
          [49]\d\d(?:
            \d{2}
          )?
        </nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3,5"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          40404|
          9(?:
            11|
            88
          )
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>
          9(?:
            11|
            88
          )
        </nationalNumberPattern>
      </tollFree>
      <!-- http://studentsabroad.state.gov/content/pdfs/911_ABROAD.pdf
           http://www.airportairport.com/American-Samoa.html
           http://www.frommers.com/destinations/americansamoa/3038020157.html -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>911</exampleNumber>
        <nationalNumberPattern>911</nationalNumberPattern>
      </emergency>
      <expandedEmergency>
        <possibleLengths national="3"/>
        <exampleNumber>988</exampleNumber>
        <nationalNumberPattern>988</nationalNumberPattern>
      </expandedEmergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="5"/>
        <exampleNumber>40400</exampleNumber>
        <nationalNumberPattern>404\d\d</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Austria (AT) -->
    <!-- http://www.rtr.at/en/tk/E129 -->
    <territory id="AT">
      <generalDesc>
        <nationalNumberPattern>[1268]\d{2,5}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="[3-6]"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          1(?:
            1(?:
              2|
              6(?:
                00[06]|
                1(?:
                  17|
                  23
                )
              )
            )|
            2[0238]|
            3[03]|
            4(?:
              [0-247]|
              5[05]|
              84
            )
          )|
          (?:
            2(?:
              066|
              20
            )|
            61|
            8108[1-3]
          )0
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3,4,6"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          1(?:
            12|
            2[0238]|
            3[03]|
            4[0-247]
          )|
          1(?:
            16\d\d|
            4[58]
          )\d
        </nationalNumberPattern>
      </tollFree>
      <!-- Added yesss! numbers 810810 , 810820 and 810830 based on their website. 
           Added Georg number 610 based on their website. -->
      <carrierSpecific>
        <possibleLengths national="[3-6]"/>
        <exampleNumber>610</exampleNumber>
        <nationalNumberPattern>
          220\d|
          610|
          (?:
            206|
            810\d
          )\d\d
        </nationalNumberPattern>
      </carrierSpecific>
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          1(?:
            [12]2|
            33|
            44
          )
        </nationalNumberPattern>
      </emergency>
      <expandedEmergency>
        <possibleLengths national="3,4,6"/>
        <exampleNumber>120</exampleNumber>
        <nationalNumberPattern>
          1(?:
            16\d{3}|
            2[038]|
            30|
            4(?:
              [0-27]|
              [58]\d
            )
          )
        </nationalNumberPattern>
      </expandedEmergency>
      <smsServices>
        <possibleLengths national="5"/>
        <exampleNumber>20600</exampleNumber>
        <nationalNumberPattern>206\d\d</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Australia (AU) -->
    <!-- http://www.itu.int/oth/T020200000D/en -->
    <!-- http://en.wikipedia.org/wiki/Telephone_numbers_in_Australia -->
    <!-- Note 200[1-3] are ignored, despite being mentioned in the ITU document, because no
         evidence that these numbers really exist could be found online, and it is unclear what
         they actually are. -->
    <territory id="AU">
      <generalDesc>
        <nationalNumberPattern>[0-27]\d{2,7}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="[3-8]"/>
        <exampleNumber>000</exampleNumber>
        <nationalNumberPattern>
          000|
          1(?:
            06|
            1(?:
              00|
              2|
              9[46]
            )|
            2(?:
              014[1-3]|
              [23]\d|
              (?:
                4|
                5\d
              )\d{2,3}|
              68[689]|
              72(?:
                20|
                3\d\d
              )|
              8(?:
                [013-9]\d|
                2
              )
            )|
            555|
            9\d{4,6}
          )|
          225|
          7(?:
            33|
            67
          )
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3,4,7"/>
        <exampleNumber>000</exampleNumber>
        <nationalNumberPattern>
          000|
          1(?:
            06|
            12|
            258885|
            55\d
          )|
          733
        </nationalNumberPattern>
      </tollFree>
      <standardRate>
        <possibleLengths national="3,4,6"/>
        <exampleNumber>225</exampleNumber>
        <nationalNumberPattern>
          1(?:
            1[09]\d|
            24733
          )|
          225|
          767
        </nationalNumberPattern>
      </standardRate>
      <!-- http://www.vodafone.com.au/personal/services/messaging/txt/mobilepremiumservices -->
      <premiumRate>
        <possibleLengths national="[4-8]"/>
        <exampleNumber>1234</exampleNumber>
        <nationalNumberPattern>
          1(?:
            2(?:
              34|
              456
            )|
            9\d{4,6}
          )
        </nationalNumberPattern>
      </premiumRate>
      <!-- http://www.vodafone.com.au/personal/services/messaging/txt/mobilepremiumservices -->
      <carrierSpecific>
        <possibleLengths national="4,7"/>
        <exampleNumber>1550</exampleNumber>
        <nationalNumberPattern>
          1(?:
            258885|
            55\d
          )
        </nationalNumberPattern>
      </carrierSpecific>
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>000</exampleNumber>
        <nationalNumberPattern>
          000|
          1(?:
            06|
            12
          )
        </nationalNumberPattern>
      </emergency>
      <smsServices>
        <possibleLengths national="[6-8]"/>
        <exampleNumber>190000</exampleNumber>
        <nationalNumberPattern>19\d{4,6}</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Aruba (AW) -->
    <!-- http://www.itu.int/oth/T020200000B/en -->
    <territory id="AW">
      <generalDesc>
        <nationalNumberPattern>[19]\d\d</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          1(?:
            00|
            18|
            76
          )|
          91[13]
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          100|
          911
        </nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>176</nationalNumberPattern>
      </carrierSpecific>
      <!-- http://www.yellowpages-aruba.com/home/emergency-numbers -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>100</exampleNumber>
        <nationalNumberPattern>
          100|
          911
        </nationalNumberPattern>
      </emergency>
      <!-- https://support.twitter.com/articles/20170024 -->
      <smsServices>
        <possibleLengths national="3"/>
        <exampleNumber>176</exampleNumber>
        <nationalNumberPattern>176</nationalNumberPattern>
      </smsServices>
    </territory>

    <!-- Åland Islands (AX) -->
    <territory id="AX">
      <generalDesc>
        <nationalNumberPattern>
          [17]\d\d(?:
            \d{2}
          )?
        </nationalNumberPattern>
      </generalDesc>
      <!-- Most service numbers are included under UAN in PhoneNumberMetadata.xml (and also in
           the no-international-dialling block) but prefixes 75[12] are always short and used for
           directory services, hence we consider them to be short numbers. -->
      <shortCode>
        <possibleLengths national="3,5"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>
          112|
          75[12]\d\d
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>112</nationalNumberPattern>
      </tollFree>
      <!-- http://www.arrivalguides.com/en/Travelguides/Europe/Finland/ALAND -->
      <emergency>
        <possibleLengths national="3"/>
        <exampleNumber>112</exampleNumber>
        <nationalNumberPattern>112</nationalNumberPattern>
      </emergency>
    </territory>

    <!-- Azerbaijan (AZ) -->
    <!-- http://www.itu.int/oth/T020200000F/en -->
    <territory id="AZ">
      <generalDesc>
        <nationalNumberPattern>[148]\d{2,3}</nationalNumberPattern>
      </generalDesc>
      <shortCode>
        <possibleLengths national="3,4"/>
        <exampleNumber>101</exampleNumber>
        <nationalNumberPattern>
          1(?:
            0[1-3]|
            12
          )|
          (?:
            404|
            880
          )0
        </nationalNumberPattern>
      </shortCode>
      <tollFree>
        <possibleLengths national="3"/>
        <exampleNumber>101</exampleNumber>
        <nationalNumberPattern>
          1(?:
            0[1-3]|
            12
          )
        </nationalNumberPattern>
      </tollFree>
      <!-- https://support.twitter.com/articles/20170024 -->
      <carrierSpecific>
        <possibleLengths national="4"/>